// Authenication
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILED = "SIGNOUT_FAILED";
export const PROCESSING = "PROCESSING";

// Movies
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE_INFO = "FETCH_MOVIE_INFO";
export const UPDATE_MOVIE = "UPDATE_MOVIE";

// Articles
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLE_INFO = "FETCH_ARTICLE_INFO";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const UPLOAD_ARTICLE = "UPLOAD_ARTICLE";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_FAILED = "ADD_ARTICLE_FAILED";

export const PROGRESS = "PROGRESS";
export const RESET = "RESET";

// Poster
export const FETCH_POSTER = "FETCH_POSTER";
export const UPLOAD_POSTER = "UPLOAD_POSTER";
export const UPDATE_POSTER_SUCCESS = "UPDATE_POSTER_SUCCESS";
export const UPDATE_POSTER_FAILED = "UPDATE_POSTER_FAILED";